apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: simulated-cloud-vault
spec:
  provider:
    fake:
      data:
        - key: "/production/database/credentials"
          value: '{"username":"cloudbees_admin","password":"MockZeroTrustPassword2026!","db_name":"enterprise_cicd"}'
        - key: "/production/cloudbees/license"
          value: '{"license_key":"CB-ENT-2026-ZERO-TRUST-MOCK","tier":"enterprise"}'
        - key: "/production/aws/ssm/jnlp-secret"
          value: "mock-jnlp-token-988310-sec"
